### ISSUE TITLE
Does support  bulk Nanopore direct RNA sequencing data?

### ISSUE THREAD

**Issue by baishengjun** [mcgilldinglab/MATES#10]
Hi,
Great jobs, does MATES support  bulk Nanopore direct RNA sequencing data? or how to modify paratemeters for bulk Nanopore direct RNA sequencing data type?

Thanks a lot,
Bai

**Comment by Szym29** [comment]
Hi Bai,

We never run MATES directly on bulk Nanopore RNA-seq data. And I don't think that MATES natively supports to train on bulk RNA-seq data. Before training MATES, the preprocessing steps to build unique and multi-mapping coverage vectors requires the data in 10X scRNA-seq (each read has a barcode) or smart-seq2 format (reads from same cells are in one bam file). However, if you manage to build unique and multi-mapping coverage vectors for your Nanopore RNA-seq data (e.g. manually assign "barcode" to each of your Nanopore reads, or similar to smart-seq data formate), you can still try MATES for the training and other downstream tasks. Currently, MATES focus on the single-cell level TE quantification and do not have a plan to support bulk RNA-seq data.

Thanks,
Yumin
