### ISSUE TITLE
How to construct TE reference for other species?

### ISSUE THREAD

**Issue by bio-xtt** [mcgilldinglab/MATES#11]
Hello, I want to build reference for species Chimpanzee, Macaca fascicularis and so on, scTE has built reference TE for these two species, I would like to ask how to build with MATES, is there a corresponding tutorial?

**Comment by Szym29** [comment]
Hello @bio-xtt ,

Thanks for your interest in using our tool. In the https://github.com/mcgilldinglab/MATES/tree/main/example, we mentioned that

If you have species other than human/mouse, downloaded TE reference in csv format and gene refrence in GTF format from UCSC table browser, run:
```sh
python build_reference.py Other path_to_TE_reference path_to_Gene_reference
```
```sh
## A sample of D.melanogaster TE refrence downloaded from UCSC table browser:
$ cat TE_reference.csv | head
#"bin","swScore","milliDiv","milliDel","milliIns","genoName","genoStart","genoEnd","genoLeft","strand","repName","repClass","repFamily","repStart","repEnd","repLeft","id"
"73","845","199","35","16","chr4","130778","131107","-1217024","-","DNAREP1_DM","RC","Helitron","-82","512","268","8"
"74","18658","190","35","41","chr4","1307882","1314210","-33921","-","HETA","LINE","Jockey","-1","6080","1","8"
"585","416","0","0","0","chr4","0","355","-1347776","+","(TTATTATA)n","Simple_repeat","Simple_repeat","1","355","0","8"
"585","15","134","29","29","chr4","688","723","-1347408","+","(TAA)n","Simple_repeat","Simple_repeat","1","35","0","8"
```
You can also follow [UCSC table browser use guide](https://github.com/mcgilldinglab/MATES/blob/main/tutorial/reference_downloading.md) to download TE and gene reference.

Thanks,
Yumin

**Comment by bio-xtt** [comment]
Thank you very much. The following error occurred when I constructed human TE reference. How can I solve it?
![image](https://github.com/user-attachments/assets/a5252e61-0624-4fb5-aaa8-0afb1af04a0d)

**Comment by Szym29** [comment]
Hi @bio-xtt ,

I have fixed this issue and updated the code. Please git clone the code again. 

Thanks for your interest. Please feel free to contact us if you have any further issues.

Best,
Yumin

**Comment by bio-xtt** [comment]
Thank you very much

**Comment by bio-xtt** [comment]
Hello, I used the following command to construct TE references for other species, and the following error occurred. How should I solve it
`python3 build_reference.py  --species  Other  --other_species_TE  /work/xtt/biosoft/Mmul_10/Macaca_rmsk.csv  --other_species_GTF  /work/xtt/biosoft/Mmul_10/Macaca_fascicularis.Macaca_fascicularis_5.0.102.gtf`

**TE file:**
![image](https://github.com/user-attachments/assets/643672e7-2088-4259-b4a9-2a5bed832946)

**GTF file**
![image](https://github.com/user-attachments/assets/fe24a3ec-125f-42cd-902d-012cc9c857ae)

**erorr information:**
![image](https://github.com/user-attachments/assets/c1cd8da0-d252-4027-9961-38e24dd28187)

**Comment by Szym29** [comment]
Hi @bio-xtt ,

Can you update the code again? I have fixed this issue. Thanks.
