### ISSUE TITLE
Issues splitting BAM files for every cell 

### ISSUE THREAD

**Issue by HannePuype** [mcgilldinglab/MATES#14]
Hi! 
Thank you for developing this tool!

I am trying to run MATES with my data (the test data works) on an HPC environment. However, splitting my BAM files into a BAM file for each cell takes too long. I can only submit jobs on the HPC that last 72 hours, which is too short. How do you handle this with your data? Or am I missing something? I have tried using one sample to see if it works, so I used one thread as recommended. 

Thank you for your help!
Kind regards,
Hanne

**Comment by Szym29** [comment]
Hi @HannePuype ,

Thank you for your interest in using our tool! Are you using 10X data or smart-seq data? If it's 10X, you can use more threads. For 10X data, one sample would have thousands of cells, and one thread will process one cell instead of the whole sample at a time , so you can use more threads as you wanted. This could significantly improve the running efficiency. If you are using smart-seq data, this shouldn't be that long since one sample only represents one cell.

Thanks,
Yumin

**Comment by HannePuype** [comment]
Hi Yumin

Thank you for your quick answer!  
I am using 10X data.  
I am not sure whether using more threads will solve it (but correct me if I'm wrong), because in the MATES script _bam_processor.py_, the following line is executed for the number of batches  
`batch_size = math.ceil(sample_count / threads_num)`.  
So even when I use e.g. 6 threads, the batch size will still be rounded to 1 (one sample) and the splitting will be done per cell and not in parallel.   

Kind regards,
Hanne

**Comment by Szym29** [comment]
Hi @HannePuype ,

Please kindly check our MATES v0.1.3. Can you check if the `bam_propcessor.split_count_10X_data()` can help you speed up the preprocessing? We will further improve the efficiency.

Thanks,
Yumin

**Comment by HannePuype** [comment]
Hi Yumin

Great, thank you! I will test it out as soon as possible and will let you know how it goes!

Hanne

**Comment by HannePuype** [comment]
Hi Yumin

I have tried the new function. It took a while because I had to increase the memory every time.

The last time I submitted my job on the cluster, I used 500GB of memory and 72 hours. However, this was not sufficient. The unique and multi coverage vectors were built, but the processing of the barcodes was not complete yet. I think the 500GB was also not sufficient at the end. I had a rather large BAM file of 22GB, so maybe it would have been completed with a smaller one. 

I am looking forward to further efficiency improvement and will certainly test out MATES again when I have a smaller dataset! 

Thank you for your time,
Hanne

**Comment by Szym29** [comment]
Hi @HannePuype ,

Could you please update the MATES to v0.1.5 and follow this[ jupyter notebook ](https://github.com/mcgilldinglab/MATES/blob/main/example/sample_pipeline.ipynb) to run your data using `bam_processor.split_count_10X_data()`? I re-implemented the `bam_processor.split_count_10X_data()` function to achieve a better balance between running time and memory. In current v0.1.5, I don't think memory would be an issue. 

We recently help one of our user to test their data, their bam file is about 30GB and MATES finished with in 6 hours. But the running efficiency would also be affected by the power of HPC and the total number of cells in your data.

Thanks,
Yumin
