### ISSUE TITLE
the correspondence between the numerical identifiers in the output matrix and the transposable elements

### ISSUE THREAD

**Issue by huangzr123** [mcgilldinglab/MATES#16]
I am encountering difficulties in downstream analysis due to the inability to locate the correspondence between the numerical identifiers in the output matrix and the subfamily and loci of transposable elements.

I have successfully run MATES on 10x Visium data, resulting in the generation of an h5ad file (../10X_locus/X/combined_matrix.h5ad) and an expression matrix (../result_MTX/X/TE_MTX.csv). However, the row names in these files appear to be numerical values. I would like to confirm if these are the final output files. Additionally, could you please advise on how to obtain the correspondence between these numerical values and the specific subfamilies and loci of the transposable elements?

Thank you for your help!
Kind regards,
Zurui

**Comment by Szym29** [comment]
Hi @huangzr123 ,

May I ask would you be interested in locus level TE expression or subfamily level? The 'combined_matrix.h5ad' file contains the TE expression in the locus level. And you can map these numerical values back to the TE reference file sent to MATES. We are currently working on the new function to showing these results in the same manner as in our manuscript, like 'chr3∣75551382∣75558968∣ + ∣HERVK − int∣ERVK, 7586 bp'. See also my latest reply to #13 for details. 

The expression matrix (../result_MTX/X/TE_MTX.csv) contains the subfamily level information, you can combine this csv table with your 10x visium h5ad file following this [tutorial](https://github.com/mcgilldinglab/MATES/blob/main/tutorial/scRNA/10X/scRNA_10X_GeneTE_Analysis.ipynb). There is a section called 'TE' and it shows you how to combine the produced csv file with h5ad to do downstream analysis.

Please let me know if you have any other question.

Thanks,
Yumin

**Comment by huangzr123** [comment]
> Hi @huangzr123 ,
> 
> May I ask would you be interested in locus level TE expression or subfamily level? The 'combined_matrix.h5ad' file contains the TE expression in the locus level. And you can map these numerical values back to the TE reference file sent to MATES. We are currently working on the new function to showing these results in the same manner as in our manuscript, like 'chr3∣75551382∣75558968∣ + ∣HERVK − int∣ERVK, 7586 bp'. See also my latest reply to #13 for details.
> 
> The expression matrix (../result_MTX/X/TE_MTX.csv) contains the subfamily level information, you can combine this csv table with your 10x visium h5ad file following this [tutorial](https://github.com/mcgilldinglab/MATES/blob/main/tutorial/scRNA/10X/scRNA_10X_GeneTE_Analysis.ipynb). There is a section called 'TE' and it shows you how to combine the produced csv file with h5ad to do downstream analysis.
> 
> Please let me know if you have any other question.
> 
> Thanks, Yumin

Thanks! My question has been fixed! Nice work

**Comment by huangzr123** [comment]
Sorry, when I test the h5ad output, I found the TE_index is duplicated?

table(duplicated(CRC4_loci@assays$RNA@meta.features$TE_index))
 FALSE   TRUE 
118628  15414

**Comment by Szym29** [comment]
See also #18

**Comment by Szym29** [comment]
Hi @huangzr123 ,

The generated h5ad file can also show the TE locus information (Chromosome|start|end|TE_name).

Thanks,
Yumin
