### ISSUE TITLE
build reference error

### ISSUE THREAD

**Issue by lxinghua** [mcgilldinglab/MATES#17]
Hi,
I followed your tutorial to download and build references for other species.
My command is this:
`python build_reference.py --species Other --other_species_TE TE_reference.csv --other_species_GTF Gene_reference.gtf`
However, it shows the following error:

> Traceback (most recent call last):
  File "/Users/xinghua/Downloads/build_reference.py", line 154, in <module>
    main()
  File "/Users/xinghua/Downloads/build_reference.py", line 58, in main
    genes = genes[genes['Feature'] == 'gene']
            ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xinghua/miniconda3/lib/python3.12/site-packages/pyranges/pyranges_main.py", line 436, in __getitem__
    return _getitem(self, val)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/xinghua/miniconda3/lib/python3.12/site-packages/pyranges/methods/getitem.py", line 33, in _getitem
    raise Exception("Not a valid subsetter: {}".format(str(val)))
Exception: Not a valid subsetter: False

Can you help figure this out? Or could you share the format of the expected references?

Thanks!

**Comment by Szym29** [comment]
Hi @lxinghua ,

It looks like the format of GTF you are using is not Ensembl format, which has 'gene' keyword in the gtf file. If you are using NCBI refseq format GTF, the keyword should be 'transcript'. As you can in the attached screenshot, NCBI has several format of gene annotation file (The track tab). If the species you want to process has the Ensembl format, you can download it and re-process. But if you can only find the NCBI Refseq or other format, please share the format of track with us. 

I will also update the build_reference.py file to support NCBI Refseq format today.

Thanks,
Yumin

<img width="1512" alt="Screenshot 2024-11-06 at 13 22 20" src="https://github.com/user-attachments/assets/f61c476b-bf76-4501-a36c-4f2703efcced">

**Comment by Szym29** [comment]
Hi @lxinghua ,

I also quickly update the build_reference.py file. If you are using the ensemble or GENOCDE GTF format, the updated code may solve your issue.

Thanks,
Yumin

**Comment by Szym29** [comment]
Hi @lxinghua ,

Thanks for your feedback. We realized the previous tutorial might be misleading and code is not user friendly enough. So we have enhanced the step by step tutorial of reference genome building tutorial and the script. 

To avoid the confusion, can you check our latest [reference genome building tutorial](https://github.com/mcgilldinglab/MATES/blob/main/tutorial/reference_downloading.md) and update the code to the latest version (v0.1.4)?

Thanks,
Yumin
