### ISSUE TITLE
torch version

### ISSUE THREAD

**Issue by BitterWood** [mcgilldinglab/MATES#19]
As I install MATES just now, I found the torch version 2.0.1 figured in the requirements.txt incompatible with MATES 0.1.4, thus throwing a fatal error. I correct this mistake and install MATES successfully. This may be a minor mistake.

**Comment by Szym29** [comment]
Hi @BitterWood ,

Thank you for using our tool and catching this error. We no longer use the requirements.txt to install environments. We will remove the requirements.txt in the next update. You can directly install MATES with `pip install .`

Thanks,
Yumin

**Comment by BitterWood** [comment]
Hi @Szym29.
Thank you for your quick reply. Actually I installed MATES following [example](https://github.com/mcgilldinglab/MATES/tree/main/example), so this page may also need to be corrected.

**Comment by Szym29** [comment]
Hi @BitterWood ,

Thanks for the reminder. I have also updated the one you mentioned to keep it the same as the main repo webpage.

Thanks,
Yumin

**Comment by BitterWood** [comment]
By the way, do I need to re-install MATES via `pip install` and re-run the pipeline? I met some error and solve the problems by correcting the source script, but I'm afraid I installed the elder version of MATES following the example, and I may not need to do the correction by installing the latest version.

**Comment by Szym29** [comment]
Hi,

I don't think you have to. Would you mind sharing the errors you experienced with us? Recently, we are actively developing this tool to add some functions, so the example script or interface might be out-dated. If you can share the errors with us, we can double check and see if the errors come from the example script or our codes.

Thanks,
Yumin

**Comment by BitterWood** [comment]
Thank you for your reply :）. I will open another issue to share about the errors.
