### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by YiweiNiu** [mcgilldinglab/MATES#2]
Hi,

Thanks for developing such a useful tool. I would like to try it, but I encountered errors when intalling it.

First, there are some `@ file:///home/ktietz/src/ci/alabaster_1611921544520/work` in the `requirements.txt`, and pip will throw errors.

Second, I found there is a `MATES` in the `requirements.txt`. So, I tried to install it directly using `pip install MATES`. The installation was smooth, but it had issues when importing this module

```py
>>> import MATES
>>> from MATES import bam_processor
>>> from MATES import data_processor

>>> from MATES import MATES_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/home/software/MATES/MATES/MATES_model.py", line 4, in <module>
    from MATES.scripts.make_prediction_locus import make_prediction_locus
ModuleNotFoundError: No module named 'MATES.scripts.make_prediction_locus'
```

Thanks in advance!

**Comment by Szym29** [comment]
Hi,

Thanks for your feedback. We made some modifications a few days ago and probably failed to sync all codes to github. We will fix it ASAP.

Thanks!

**Comment by Szym29** [comment]
Hi @YiweiNiu,

Sorry for the delayed response. The requirements.txt issue is fixed and we also have updated a version of MATES that you can use the following steps to install and use MATES.

```
git clone https://github.com/mcgilldinglab/MATES.git
cd MATES
pip3 install -r requirements.txt 
python setup.py install```

Thanks,
Yumin

**Comment by YiweiNiu** [comment]
Hi, thanks for the update. I was wondering which Python version you're using for MATES, as I have some package conflicting issues when using python 3.11.3 to install the requirements.

**Comment by Szym29** [comment]
I use python3.9, it looks alright.

**Comment by YiweiNiu** [comment]
Hi, thanks for your reply. I have managed to install MATES now, but when importing the modules there's an error:

```py
>>> import MATES
>>> from MATES import bam_processor
>>> from MATES import data_processor

>>> from MATES import MATES_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/home/software/MATES/MATES/MATES_model.py", line 4, in <module>
    from MATES.scripts.make_prediction_locus import make_prediction_locus
ModuleNotFoundError: No module named 'MATES.scripts.make_prediction_locus'
>>> from MATES import TE_quantifier
>>> 
```

**Comment by Szym29** [comment]
will fix it today. 
thanks.

**Comment by Szym29** [comment]
Hi @YiweiNiu,

I have uploaded the missing script. Thank you very much for pointing the issue. We are working on the revision and don't have much time to test it thoroughly. But we will make sure it's bug free in the upcoming weeks. If you have any other issue while using MATES, please let us know. 

Thank you,
Yumin
