### ISSUE TITLE
Fail to download sample data

### ISSUE THREAD

**Issue by BitterWood** [mcgilldinglab/MATES#21]
Hi @Szym29 ,
Thanks for the nice tool, but I encounter some problems recently. Could you please offer some advice?

As I try to download sample data from [here](https://mcgill-my.sharepoint.com/:u:/g/personal/ruohan_wang4_mail_mcgill_ca/EdwyzdHz1KtLr9G_c503mwsB6Y4-lawnqEQ1NBx_1Mn9tQ?e=YkcH1B), it came with the error: 404 FILE NOT FOUND. Is the link out-dated?

By the way, the splitting bam step costs too much time for my custom bam file. To be specific, I call for 60 cpus and 240G memory from cluster, and split the bam file with
`bam_processor.split_count_10X_data("exclusive","10X",60,"../sample_list.txt","../bam_path.txt","../bc_path.txt","CR","Default")` or 
`bam_processor.split_bam_files('10X', threads_num=60, sample_list_file="../sample_list.txt", bam_path_file="../bam_path.txt", bc_ind="CR", bc_path_file="../bc_path.txt")
bam_processor.count_coverage_vec("exclusive", '10X', threads_num=60, sample_list_file="../sample_list.txt", TE_ref_path="Default", bc_path_file="../bc_path.txt")`
I have tried both codes. For both codes, some bam files got frozen within 24hrs  while others are estimated to finish splitting by 18000hrs. I read through issues and examples but fail to see the problem.

The sample_list.txt file:
> custom

The bam_path.txt file:
> ../custom_resAligned.sortedByCoord.out.bam

The bc_path.txt file:
> ../bc.tsv

Thr first six lines of bc.tsv file:
> CAAGCTGCATGTGGAT
GTGGATCCTGAGAACT
CATGTGGATCCTGAGA
CTTCAGGCTCCTGGGC
TTCACCCCCGCTGCAC
CAAGAAAGTGATAACT
CCATCACTGGAAAGAG
GCCATCACTGGAAAGA
TGGAAAGAGAGGCCCA
GAACAACATTATGAAC

The first six lines of custom_resAligned.sortedByCoord.out.bam via samtools:
> custom.28298482    16      chr1    3000010 0       18M10S  *       0       0       TATTTTGTGGTTACTTTGTACTGTCCGG    FFFFFFFFFFFFFFFFFFFFFFFFFFFF    CR:Z:CAAGCTGCATGTGGAT   UR:Z:CCTGAGAACT CY:Z:FFFFFFFFFFFFFFFF UY:Z:FFFFFFFFFF NH:i:6  HI:i:1  CB:Z:-  UB:Z:-
custom.124311820   16      chr1    3000010 0       18M10S  *       0       0       TATTTTGTGGTTACTTTGTACTGTCCGG    FFFFFFFFFFFFFFFFFFFFFFFFFFFF    CR:Z:GTGGATCCTGAGAACT   UR:Z:TCAGGCTCCT CY:Z:FFFFFFFFFFFFFFFF UY:Z:FFFFFFFFFF NH:i:6  HI:i:1  CB:Z:-  UB:Z:-
custom.405852817   16      chr1    3000010 0       18M10S  *       0       0       TATTTTGTGGTTACTTTGTACTGTCCGG    FFF:FFFFFFFFFFFFFFFFFFFFFFFF    CR:Z:CATGTGGATCCTGAGA   UR:Z:ACTTCAGGCT CY:Z:FFFFFFFFFFFFFFFF UY:Z:FFFFFFFFFF NH:i:6  HI:i:1  CB:Z:-  UB:Z:-
custom.422531695   16      chr1    3000010 0       18M10S  *       0       0       TATTTTGTGGTTACTTTGTACTGTCCGG    :FFFFFFF::FF:FFFFFF:FFFF,FFF    CR:Z:CTTCAGGCTCCTGGGC   UR:Z:AATATGATCG CY:Z:,:FFFFFFFFFFFF:F UY:Z:FF:FFFFFF, NH:i:6  HI:i:1  CB:Z:-  UB:Z:-
custom.430044149   16      chr1    3000010 0       18M10S  *       0       0       TATTTTGTGGTTACTTTGTACTGTCCGG    FFFFFFFFFFFFFFFFFFFFFFFFFFFF    CR:Z:TTCACCCCCGCTGCAC   UR:Z:AGGCTGCCTT CY:Z:FFFFFFFFFFFFFF,F UY:Z:FFFF:FFFFF NH:i:6  HI:i:1  CB:Z:-  UB:Z:-
custom.443212001   16      chr1    3000010 0       18M10S  *       0       0       TATTTTGTGGTTACTTTGTACTGTCCGG    FFFF:FFFFF:FFFFFFFFFFFFFFFFF    CR:Z:CAAGAAAGTGATAACT   UR:Z:GCCTTTAACG CY:Z:FFFFFFFFFFFFFFFF UY:Z:FFFFFFFFFF NH:i:6  HI:i:1  CB:Z:-  UB:Z:-
custom.128424953   16      chr1    3000136 3       12M164474N16M   *       0       0       ATTGATGACTGTCCTAAGCCTTTCCCAC    ,:F,FFFFFFFFFF,FFFFF:FFFFF:F    CR:Z:CCATCACTGGAAAGAG   UR:Z:AGGCCCATTG CY:Z:,F,FFF:FFFFF:,FF UY:Z:FF,F,FF,:F NH:i:2  HI:i:1  CB:Z:-  UB:Z:-
custom.164381729   16      chr1    3000136 3       12M164474N16M   *       0       0       ATTGATGACTGTCCTAAGCCTTTCCCAC    FFFFFFFFFFFFFFFFFFFFFFFFFFFF    CR:Z:GCCATCACTGGAAAGA   UR:Z:GAGGCCCATT CY:Z:FFFFFFFFFFFFFFFF UY:Z:FFFFFFFFFF NH:i:2  HI:i:1  CB:Z:-  UB:Z:-
custom.184473425   16      chr1    3000136 3       12M164474N16M   *       0       0       ATTGATGACTGTCCTAAGCCTTTCCCAC    FFFFFFFFFFFFFFFFFFFFFFFFFFFF    CR:Z:TGGAAAGAGAGGCCCA   UR:Z:TTGGACACGC CY:Z:FFFFFFF,FFFFFFFF UY:Z:FFFFFFFFFF NH:i:2  HI:i:1  CB:Z:-  UB:Z:-
custom.432945021   16      chr1    3000136 3       12M164474N16M   *       0       0       ATTGATGACTGTCCTAAGCCTTTCCCAC    FFFFFFFFFFFFFFFFFFFFFFFFFFFF    CR:Z:GAACAACATTATGAAC   UR:Z:TAACCAGTAC CY:Z:FFFFFFFFFFFFFFFF UY:Z:FFFFFFFFFF NH:i:2  HI:i:1  CB:Z:-  UB:Z:-

Any advice will be highly appreciated.

**Comment by Szym29** [comment]
Hi @BitterWood ,

Thank you for pointing out the expired link to sample data. I have updated the link. What is the size of your data? and how many cells do you have? If the data is large, normally it takes 1-2 days to finish runing `the bam_processor.split_bam_files()` and `bam_processor.count_coverage_vec()`. There are some logs, you can check the progress in ./unique_read/custom/split_barcode.log,./unique_read/custom/by_barcode/custom_unique_splitting.log , ./multi_read/custom/split_barcode.log, and ./multi_read/custom/by_barcode/custom_multi_splitting.log.

Can you run the sample data to make sure everything works well on your end? In our manuscript, our data is about tens GBs and several thousands cells. It took about 2 days to run  split_bam_files() and count_coverage_vec(). We are working on this efficiency issue to find a better balance between running time and memory usage.

Thanks,
Yumin

**Comment by BitterWood** [comment]
Hi @Szym29 .

Thank you for your quick reply. The sample data works on my end.
After careful inspection, I suppose my custom bam file created by STARsolo is of some mistakes. Specifically STARsolo seems to incorrectly extract CR from fastq files, and the bam file contains ~18,000 cells, which is bound to be wrong. My questions are as follows:

1. Can I use the bam file created by CellRanger instead of STARsolo? The bam file  created by CellRanger seems to be OK, but I'm not sure whether it deals with multi-reads correctly.
2. Considering these codes: `bam_processor.split_count_10X_data(TE_mode,data_mode, threads_num, sample_list_file, bam_path_file, bc_path_file, bc_ind='CR', ref_path = 'Default')`  and 
`bam_processor.split_bam_files('10X', threads_num, sample_list_file, bam_path_file, bc_ind, bc_path_file)
bam_processor.count_coverage_vec(TE_mode, '10X', threads_num, sample_list_file, TE_ref_path, bc_path_file)`
For large bam files, some examples or issues recommend the former while others recommend the latter. Which one do you recommend for this issue?
3. By the way, I can't see the log files both for the sample data and my custom data:
./unique_read/custom/split_barcode.log,./unique_read/custom/by_barcode/custom_unique_splitting.log , ./multi_read/custom/split_barcode.log, and ./multi_read/custom/by_barcode/custom_multi_splitting.log.

Many thanks for your generous help!

**Comment by BitterWood** [comment]
Sorry for the missing points. My bam files are of 8-9 GBs.

**Comment by Szym29** [comment]
Hi @BitterWood ,

> Can I use the bam file created by CellRanger instead of STARsolo? The bam file created by CellRanger seems to be OK, but I'm not sure whether it deals with multi-reads correctly.

Bam files generated by CellRanger didn't keep the multiple mapping reads.

> For large bam files, the https://github.com/mcgilldinglab/MATES/issues/14recommend the former while [example](https://github.com/mcgilldinglab/MATES/tree/main/example) recommend the latter. Could you please give a recommendation for this issue?

If your memory is large enough, I would recommend using split_count_10X_data(). But if not, you can use the latter. 

> Is multi-threads function available now? The README file says it's under development while https://github.com/mcgilldinglab/MATES/issues/14says it's available for 10X data. I have a try by setting threads_num to be 10, but that seems not to accelerate the speed when dealing with the sample data.

For 10X, it's still under development. This function got some delays.

**Comment by BitterWood** [comment]
Hi @Szym29 ,
Thank you for your reply!
I've finished the MATES task but forget to update here.
The log files failed to be generated before due to the memory problem.

**Comment by Szym29** [comment]
Hi @BitterWood ,

Good to know you have run MATES successfully. Good luck and thanks for your feedback.

Best,
Yumin
