### ISSUE TITLE
python build_reference.py --species Human

### ISSUE THREAD

**Issue by l1y1y** [mcgilldinglab/MATES#22]
--2024-11-20 17:58:39--  https://www.repeatmasker.org/genomes/hg38/RepeatMasker-rm405-db20140131/hg38.fa.out.gz
Resolving www.repeatmasker.org (www.repeatmasker.org)... 174.127.185.143
Connecting to www.repeatmasker.org (www.repeatmasker.org)|174.127.185.143|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 184414867 (176M) [application/x-gzip]
Saving to: ‘hg38.fa.out.gz’

100%[==================================================================================================================================================================================================================================>] 184,414,867  809KB/s   in 2m 27s 

2024-11-20 18:01:07 (1.20 MB/s) - ‘hg38.fa.out.gz’ saved [184414867/184414867]

--2024-11-20 18:01:14--  https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_40/gencode.v40.primary_assembly.annotation.gtf.gz
Resolving ftp.ebi.ac.uk (ftp.ebi.ac.uk)... 193.62.193.165
Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.193.165|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48052164 (46M) [application/x-gzip]
Saving to: ‘gencode.v40.primary_assembly.annotation.gtf.gz’

100%[==================================================================================================================================================================================================================================>] 48,052,164  12.4MB/s   in 4.5s   

2024-11-20 18:01:19 (10.2 MB/s) - ‘gencode.v40.primary_assembly.annotation.gtf.gz’ saved [48052164/48052164]

Traceback (most recent call last):
  File "/public/home/zzs000213/Bioinformation_software/MATES/build_reference.py", line 183, in <module>
    main()
  File "/public/home/zzs000213/Bioinformation_software/MATES/build_reference.py", line 39, in main
    TEs = pd.read_csv(f'{species.lower()}_TEs.csv')
  File "/public/home/zzs000213/.conda/envs/mates/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/public/home/zzs000213/.conda/envs/mates/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/public/home/zzs000213/.conda/envs/mates/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/public/home/zzs000213/.conda/envs/mates/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/public/home/zzs000213/.conda/envs/mates/lib/python3.9/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'human_TEs.csv'

I have encountered this error many times

**Comment by l1y1y** [comment]
I installed it on the server, following the code and steps you gave, the command is python build_reference.py --species Human

**Comment by Szym29** [comment]
Did you install it using `pip install .` or `pip install MATES`? Did you try to run the commands provided in https://github.com/mcgilldinglab/MATES/blob/main/example/sample_pipeline.ipynb? And change the `python ../build_reference.py --species Mouse` to Human?

**Comment by l1y1y** [comment]
I'm not using pip, I'm using the # Clone the MATES repository
git clone https://github.com/mcgilldinglab/MATES.git

# Create a new environment
conda create -n mates_env python=3.9
conda activate mates_env

# Install required packages
conda install -c bioconda samtools -y
conda install -c bioconda bedtools -y

# Install MATES
cd MATES
pip install .

# Add environment to Jupyter Notebook
conda install ipykernel
python -m ipykernel install --user --name=mates_env

**Comment by Szym29** [comment]
Did you see any new files downloaded and generated to the folder you run this command? You should also see 'hg38.fa.out', 'gencode.v40.primary_assembly.annotation.gtf' and a csv file called 'human_Genes.csv'

**Comment by l1y1y** [comment]
Yes, there are these files, and a human_TEs_tmp.csv

**Comment by Szym29** [comment]
Would you be able to open the human_TEs_tmp.csv file and see if it has some contents?

**Comment by l1y1y** [comment]
Sorry I deleted these, I think this is a failure, maybe I had a problem with the runtime, I'm going to start with a new installation

**Comment by Szym29** [comment]
If the issue is still there after re-installation, and you can only see  human_TEs_tmp.csv, can you try the following codes to get human_TEs.csv manually?

```
te_csv = 'human_TEs_tmp.csv'
TEs = pd.read_csv(te_csv, header=None)
TEs = TEs.rename(columns={0: 'TE_chrom', 1: 'start', 2: 'end', 3: 'score', 4: 'strand', 5: 'TE_Name', 6: 'TE_Fam'})
TEs['strand'] = TEs['strand'].apply(lambda x: '-' if x == 'C' else x)
TEs['class'] = TEs['TE_Fam'].apply(lambda x: x.split('/')[0])
TEs = TEs[TEs['class'].isin(['DNA', 'LTR', 'RC', 'Retroposon', 'SINE', 'LINE'])]
TEs = TEs.iloc[:, :-1]

TEs.to_csv('human_TEs.csv', index=False)
```

**Comment by l1y1y** [comment]
Okay, well, if it's still a problem, I'll try.

**Comment by l1y1y** [comment]
I reinstalled it once, and still have the same problem. human_TEs_tmp.csv is a 200+M file
Building wheel for MATES (setup.py) ... done
  Created wheel for MATES: filename=MATES-0.1.4-py3-none-any.whl size=53897 sha256=67052f93301b36e0f7271fd16153fc2bed4f553d3b3c19c037f175946ea2e050
  Stored in directory: /tmp/pip-ephem-wheel-cache-5ml7a872/wheels/ef/7c/1d/fd5587b12eb64d0083657532c3def4ed946fb1ffe070b720f1
Successfully built MATES
Installing collected packages: pytz, mpmath, lit, zipp, tzdata, typing-extensions, tqdm, tabulate, sympy, six, pysam, pyparsing, pillow, packaging, nvidia-nvtx-cu11, nvidia-nccl-cu11, nvidia-cusparse-cu11, nvidia-curand-cu11, nvidia-cufft-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, numpy, networkx, natsort, MarkupSafe, kiwisolver, fonttools, filelock, cycler, cmake, sorted-nearest, scipy, python-dateutil, pybedtools, nvidia-cusolver-cu11, nvidia-cudnn-cu11, ncls, jinja2, importlib-resources, h5py, contourpy, pandas, matplotlib, pyranges, anndata, triton, torch, MATES
Successfully installed MATES-0.1.4 MarkupSafe-3.0.2 anndata-0.8.0 cmake-3.31.0.1 contourpy-1.3.0 cycler-0.12.1 filelock-3.16.1 fonttools-4.55.0 h5py-3.12.1 importlib-resources-6.4.5 jinja2-3.1.4 kiwisolver-1.4.7 lit-18.1.8 matplotlib-3.7.2 mpmath-1.3.0 natsort-8.4.0 ncls-0.0.68 networkx-3.2.1 numpy-1.25.2 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-cupti-cu11-11.7.101 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 nvidia-cufft-cu11-10.9.0.58 nvidia-curand-cu11-10.2.10.91 nvidia-cusolver-cu11-11.4.0.1 nvidia-cusparse-cu11-11.7.4.91 nvidia-nccl-cu11-2.14.3 nvidia-nvtx-cu11-11.7.91 packaging-24.2 pandas-2.0.0 pillow-11.0.0 pybedtools-0.10.0 pyparsing-3.0.9 pyranges-0.0.129 pysam-0.22.1 python-dateutil-2.9.0.post0 pytz-2024.2 scipy-1.11.2 six-1.16.0 sorted-nearest-0.0.39 sympy-1.13.3 tabulate-0.9.0 torch-2.0.0 tqdm-4.66.1 triton-2.0.0 typing-extensions-4.12.2 tzdata-2024.2 zipp-3.21.0

**Comment by Szym29** [comment]
can you use the following code to open the human_TEs_temp.csv?

```bash
te_csv = 'human_TEs_tmp.csv'
TEs = pd.read_csv(te_csv, header=None)
TEs = TEs.rename(columns={0: 'TE_chrom', 1: 'start', 2: 'end', 3: 'score', 4: 'strand', 5: 'TE_Name', 6: 'TE_Fam'})
TEs['strand'] = TEs['strand'].apply(lambda x: '-' if x == 'C' else x)
TEs['class'] = TEs['TE_Fam'].apply(lambda x: x.split('/')[0])
TEs = TEs[TEs['class'].isin(['DNA', 'LTR', 'RC', 'Retroposon', 'SINE', 'LINE'])]
TEs = TEs.iloc[:, :-1]

TEs.to_csv('human_TEs.csv', index=False)
```

**Comment by l1y1y** [comment]
The files I generated are these gencode.v40.primary_assembly.annotation.gtf、hg38.fa.out、hg38.new.out、hg38_TEs_tmp.csv 
I've changed hg38_TEs_tmp.csv to human_TEs.csv.

**Comment by l1y1y** [comment]
This is the converted file
TE_chrom,start,end,score,strand,TE_Name,TE_Fam
chr1,11485,11676,(248944746),-,L1MC5a,LINE/L1
chr1,11678,11780,(248944642),-,MER5B,DNA/hAT-Charlie
chr1,15265,15355,(248941067),-,MIR3,SINE/MIR
chr1,16363,16459,(248939963),-,Charlie15a,DNA/hAT-Charlie
chr1,18907,19048,(248937374),+,L2a,LINE/L2
chr1,19972,20405,(248936017),+,L3,LINE/CR1
chr1,20531,20679,(248935743),+,Plat_L3,LINE/CR1
chr1,21949,22075,(248934347),+,MLT1K,LTR/ERVL-MaLR
chr1,23120,23371,(248933051),-,MIR,SINE/MIR
chr1,23804,23824,(248932598),+,L2a,LINE/L2
chr1,23825,24011,(248932411),+,L2b,LINE/L2
chr1,24012,24038,(248932384),+,L2a,LINE/L2

**Comment by l1y1y** [comment]
Why am I having this problem? It's already been solved.

**Comment by Szym29** [comment]
So you didn't encounter any issue by using the codes I provided to convert hg38_TEs_tmp.csv to human_TEs.csv? 

That is strange. These codes are incorporated in the build_reference.py. See https://github.com/mcgilldinglab/MATES/blob/main/MATES/scripts/Ref2csv.py#L63.

Running build_reference.py will call Ref2csv.py to generate those files you mentioned, and automatically convert hg38_TEs_tmp.csv to human_TEs.csv. It looks like the software on your end stopped at somewhere between line 63 to line 72 in https://github.com/mcgilldinglab/MATES/blob/main/MATES/scripts/Ref2csv.py. So you don't have the Human_TEs.csv and Human_Genes.csv files.

However, I am not able to reproduce this error in my end, so I cannot figure out what causes this issue.

But here is another way, we provided another way in build_reference.py to build your own reference TEs and Genes. You can follow [this tutorial](https://github.com/mcgilldinglab/MATES/blob/main/tutorial/reference_downloading.md) to download the human GTF and human repeats. And then use 
`python build_reference.py --species Other --other_species_TE path_to_your_TE --other_species_GTF path_to_your_GTF --output_prefix Human` 
to generate necessary files. 

Thanks

**Comment by l1y1y** [comment]
Okay, thank you. I'll try another device.

**Comment by l1y1y** [comment]
Can you give me a more detailed copy of the installation? Will the following do?git clone https://github.com/mcgilldinglab/MATES.git
conda create -n mates_env python=3.9
conda activate mates_env
conda install -c bioconda samtools
pip install pysam
conda install -c bioconda bedtools
pip install pybedtools
cd MATES
pip3 install -r requirements.txt 
python setup.py install
pip install .
pip install velocyto

conda install ipykernel
python -m ipykernel install --user --name=mates_env

**Comment by Szym29** [comment]
Now these scripts should work

```bash
# Clone the MATES repository
git clone https://github.com/mcgilldinglab/MATES.git

# Create a new environment
conda create -n mates_env python=3.9
conda activate mates_env

# Install required packages
conda install -c bioconda samtools -y
conda install -c bioconda bedtools -y

# Install MATES
cd MATES
pip install .

# Add environment to Jupyter Notebook
conda install ipykernel
python -m ipykernel install --user --name=mates_env
```

**Comment by l1y1y** [comment]
I didn't install my samtools with conda, will that have any effect, I think back to the whole installation process and there was only this one problem.If I don't use Jupyter Notebook,conda install ipykernel python -m ipykernel install --user --name=mates_env isn't it possible to not have the

**Comment by l1y1y** [comment]
I have samtools installed locally, the latest version is 1.21 and python is 3.9.20.

**Comment by Szym29** [comment]
That is fine.

**Comment by l1y1y** [comment]
No, it still doesn't work. I tried a new server account and this problem still have. Am I running the scripts incorrectly？ I create the conda environment with the name mates and then I run the scripts in this conda environment.

**Comment by Szym29** [comment]
Hello @l1y1y ,

Can you update the MATES to v0.1.5 and then re-run the python build_reference.py? I added some notifications to help debug some potential issues on your end.

Thanks,
Yumin

**Comment by l1y1y** [comment]
If this script runs successfully, what files are generated yah, I'm not sure if I'm running it correctly.Because I get different output files when I run it on two devices

**Comment by Szym29** [comment]
can you show me the screenshot of the full logs generated when running the script? 

By running `python build_reference.py --species Human`, you are expected to get "TE_full.bed", "TE_full.csv", "TE_nooverlap.csv", "TE_nooverlap.bed", "gene_bed.csv", and "gene_bed.bed"

**Comment by l1y1y** [comment]
Sorry, I can't find the screenshot, I remember the last one appeared to be successful, but the file I generated had human_Genes.csv, human_TEs.csv, but no gene_bed.bed

**Comment by Szym29** [comment]
Can you provide a screenshot of the logs of your script running? Sorry, the gene_bed.bed won't be generated. I believe if the logs showed the 'Reference files are generated successfully!' then everything should be correct.

**Comment by l1y1y** [comment]
I only have one more screenshot of this and the last line is successful
<img width="1802" alt="微信图片_20241122222316" src="https://github.com/user-attachments/assets/2dbe7172-661c-4ff6-a888-b421f02f25bd">

**Comment by Szym29** [comment]
Then it finishes successfully.
