### ISSUE TITLE
Fail to process aligned bam files in sample data

### ISSUE THREAD

**Issue by minqi7** [mcgilldinglab/MATES#23]
Hi @Szym29 ,

Thanks for the great tool, but I encountered some problems in the process of using it.

When I processed aligned bam files of example dataset with `bam_processor.split_count_10X_data`, it came with the error: local variable 'barcodes'referenced before assignment.

details are as follows:

> bam_processor.split_count_10X_data('exclusive','10X', 1, 'test_samplelist.txt', 'test_bam_path.txt','test_cb_path.txt',bc_ind = 'CR', ref_path = '/home/minqi/MATES/TE_nooverlap.bed')
Directory ./count_coverage created.
Start splitting and counting test data ...
[W::hts_idx_load3] The index file is older than the data file: /home/minqi/MATES/./sample_data/sorted_final_merged.bam.bai
[W::hts_idx_load3] The index file is older than the data file: /home/minqi/MATES/./sample_data/sorted_final_merged.bam.bai
building unique coverage vectors: 100%.
Unique matrix finished.
building multi coverage vectors: 100%. 
Multi matrix finished.
Traceback (most recent call last):
  File "stdin", line 1, in module
  File "/home/minqi/MATES/MATES/bam_processor.py", line 36, in split_count_10X_data
    start_split_count(bc_ind, os.path.join(cur_pwd,bam_file), os.path.join(cur_pwd,barcodes), sample, TE_mode, TE_ref_path)
  File "/home/minqi/MATES/MATES/scripts/split_count_10X.py", line 285, in start_split_count
    for bc in tqdm(barcodes, desc="Processing barcodes"):
UnboundLocalError: local variable 'barcodes' referenced before assignment

How to deal with this problem? And looking forward to your reply!

**Comment by Szym29** [comment]
Hi @minqi7 ,

It looks like you didn't specify the file directory correctly. You should either put the sample data under the 'example' folder or use the correct directory in the 'test_cb_path.txt'. You can move the sample data to the 'example' folder and directly run the provided Jupyter notebook https://github.com/mcgilldinglab/MATES/blob/main/example/sample_pipeline.ipynb. 

Thanks,
Yumin

**Comment by minqi7** [comment]
Hi @Szym29 ,

I really appreciate your prompt reply. 

Although I followed your suggestions above, the same error still appeared.

> UnboundLocalError: local variable 'barcodes' referenced before assignment

**Comment by Szym29** [comment]
Can you share the command you are using? And the bc_path_file (barcode path file) you sent to bam_processor.split_count_10X_data()

**Comment by minqi7** [comment]
Hi @Szym29 ,

Thank you very much for your help！

As you said, I updated the MATES to v0.1.5 and successfully ran the script `bam_processor.split_count_10X_data`.

Thank you again for providing such a great tool!
