### ISSUE TITLE
Directory Structure Inconsistency in bam_processor.split_count_10X_data

### ISSUE THREAD

**Issue by colejbatty** [mcgilldinglab/MATES#25]
I encountered an issue while using MATES where there's an inconsistency between how directories are created and accessed in the bam_processor.split_count_10X_data function.

Steps to reproduce:
1. Create input files:
   - sample_list_file.txt containing a single sample ID (e.g., "SN0282412")
   - bam_path_file.txt containing BAM file path
   - bc_path_file.txt containing path to barcodes.tsv

2. Run:
```python
import MATES
from MATES import bam_processor
bam_processor.split_count_10X_data('inclusive','10X', 'sample_list_file.txt', 'bam_path_file.txt', 'bc_path_file.txt')
```
Issue:
The script creates directories with structure:
sub_bam_files/SN0282412/unique
sub_bam_files/SN0282412/multi

But then attempts to access:
sub_bam_files/unique

Leading to:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/sub_bam_files/unique'

Please let me know if this is a bug or an implementation error on my end. Thanks!

**Comment by Szym29** [comment]
Hello @colejbatty ,

Thank you for using our tool. Please send me the full log of this error. 

Thanks,
Yumin

**Comment by colejbatty** [comment]
import MATES                                                                                                             >>> from MATES import bam_processor                                                                                          >>> bam_processor.split_count_10X_data('inclusive','10X', 'sample_list_file.txt', 'bam_path_file.txt', 'bc_path_file.txt')   Directory ./count_coverage created.                                                                                          Start splitting and counting SN0282412 data ...                                                                              barcode directory: /mnt/data4/Cole/SN0282412/broad/hptmp/sgurajal/bwh10x/KW11070_colejbatty/230508_10X_KW11070_bcl/cellranger-7.1.0/GRCh38/BRI-2158_hashing/outs/filtered_feature_bc_matrix/barcodes.tsv
Directory /mnt/data4/Cole/MATES1/sub_bam_files created.
Directory /mnt/data4/Cole/MATES1/sub_bam_files/SN0282412 created.
Directory /mnt/data4/Cole/MATES1/sub_bam_files/SN0282412/unique created.
Directory /mnt/data4/Cole/MATES1/sub_bam_files/SN0282412/multi created.                                                      Summarizing reads statistics: 100%|███████████████████████████████████| 668810168/668810168 [22:06<00:00, 504221.88it/s]     Writing sub-bam files: 0it [00:00, ?it/s]                                                                                    building unique coverage vectors:   0%|                                                       | 0/17314 [00:00<?, ?it/s]     Traceback (most recent call last):                                                                                             File "<stdin>", line 1, in <module>                                                                                          File "/mnt/data4/Cole/miniforge3/envs/mates_env/lib/python3.9/site-packages/MATES/bam_processor.py", line 36, in split_count_10X_data                                                                                                                       start_split_count(bc_ind, os.path.join(cur_pwd,bam_file), os.path.join(cur_pwd,barcodes), sample, TE_mode, TE_ref_path)    File "/mnt/data4/Cole/miniforge3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/split_count_10X.py", line 413, in start_split_count                                                                                                               unique_TE_index_dict, multi_TE_index_dict = generate_matrix(sample, barcodes_file, path_to_bam, TE_ref_bed, coverage_stored_dir, tag_field=barcode_field)                                                                                               File "/mnt/data4/Cole/miniforge3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/split_count_10X.py", line 345, in generate_matrix                                                                                                                 generate_unique_matrix(aligned_file,bc_list,TE_ref_bed,cur_path, coverage_stored_dir, sample_name,total_reads, path,sav_vec='True')                                                                                                                     File "/mnt/data4/Cole/miniforge3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/split_count_10X.py", line 157, in generate_unique_matrix                                                                                                          bc_exist= os.listdir(join(cur_path, 'sub_bam_files','unique'))                                                           FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data4/Cole/MATES1/sub_bam_files/unique'

**Comment by Szym29** [comment]
Hi @colejbatty ,

Thank you for pointing out this error. I have fixed it. We modified the API last week and some of them were not updated. 

You can install the latest version of MATES from GitHub. Please feel free to let me know if you encounter other issues.

Thanks,
Yumin
