### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by LindaMax001** [mcgilldinglab/MATES#26]
hello,Thank you for developing the software.When I run the example, there is no sample_data file,how do I download it ?

This error occurs when I run my own data IsADirectoryError: [Errno 21] Is a directory: How do I fix this? 

thank you

**Comment by Szym29** [comment]
Hi @LindaMax001 ,

Thank you for your interest in using our tool. To run MATES, users need to create `sample_list_file`, `bam_path_file`, and `bc_path_file` by themselves. Please read our walkthrough example and use our example data and mandatory files in https://github.com/mcgilldinglab/MATES/tree/main/example. Here is the link to download the example data https://mcgill-my.sharepoint.com/:u:/g/personal/yumin_zheng_mail_mcgill_ca/ESmJrKvPuapBiuh7noTKksIBWosum5rswiG28Sgvb-IDUg?e=5sSfkZ. 

Thanks,
Yumin
