### ISSUE TITLE
ValueError: The provided bam files don't have enough reads mapped to TE loci

### ISSUE THREAD

**Issue by DrmBee** [mcgilldinglab/MATES#27]
### Example pipeline and files to process 10X Visium data
The following is the processing of Visium_Souse-Olfactory_Sulb_possorted_genome_mam.bam data:

> #Run get_cb.py to extract all cell barcodes from the bam file
> #When it comes to your own data, you should change the directory of input bam file and output cell barcode file
> !python get_cb.py

The barcodes obtained after using the above command are like the following:
> CGATTTGTCATTAATG-1
> GCAGCCTATATCACAT-1
> TACACCGTCGTTAGTC-1
> CTTAATCGACTTAGTA-1
> ...

Then I modified get_cb.py and got the barcodes again：
> CGATTTGTCATTAATG
> GCAGCCTATATCACAT
> TACACCGTCGTTAGTC
> CTTAATCGACTTAGTA
> ...

Afterwards, I ran the following code:

> from MATES import bam_processor,data_processor,MATES_model,TE_quantifier
> ## Step1: Generate coverage vector
> bam_processor.split_count_10X_data('exclusive', '10X','sample_list.txt', 'path_to_bam.txt', 'path_to_cb.txt', bc_ind='CB', ref_path = 'TE_nooverlap.bed')

> 
> 
> ## Step2: Generate the training and prediction sample
> data_processor.calculate_UM_region('exclusive', '10X', 'sample_list.txt', bin_size=5, proportion=80, bc_path_file='path_to_cb.txt',cut_off=50)
> data_processor.generate_training_sample('10X', 'sample_list.txt', bin_size=5, proportion=80,cut_off=50)
> data_processor.generate_prediction_sample('exclusive','10X','sample_list.txt', bin_size=5, proportion=80, ref_path="TE_nooverlap.csv", bc_path_file='path_to_cb.txt',cut_off=50)
> 
> 
> ## Step3:Training and prediction
> MATES_model.train('10X', 'sample_list.txt', bin_size = 5, proportion = 80, BATCH_SIZE= 256, 
>                   AE_LR = 1e-4, MLP_LR = 1e-6, AE_EPOCHS = 2, MLP_EPOCHS = 2, DEVICE='cpu')
> MATES_model.prediction('exclusive', '10X', 'sample_list.txt', bin_size = 5, proportion = 80, 
>                        AE_trained_epochs =2, MLP_trained_epochs=2,DEVICE='cpu')
> 
> ##Step4: Quantify the TE
> TE_quantifier.unique_TE_MTX('exclusive', '10X', 'sample_list.txt', 20, bc_path_file='path_to_cb.txt')
> TE_quantifier.finalize_TE_MTX('10X', 'sample_list.txt')

Then the following result was obtained:

> Unique matrix finished
> 
> uilding multi coverage vectors: 100%|██████████| 4992/4992 [00:00<00:00, 84351.43it/s]
> Multi matrix finished
> 
> rocessing barcodes: 100%|██████████| 4992/4992 [00:00<00:00, 2063463.64it/s]
> Directory MU_Stats created.
> Start Calculating U/M region for cells in test_visium...
> 
>  0%|          | 0/4992 [00:00<?, ?it/s]
> Finish calculating U/M region for cells in test_visium, finalizing...
> Finish finalizing U/M region information for test_visium.
> 
> enerating training samples: 100%|██████████| 1/1 [00:00<00:00, 20.31it/s]
> Start generating training sample for unqiue read TE in test_visium...
> Finish analyse generating sample for unqiue read TE in test_visium.
> Start generating training sample for multi read TE in test_visium...
> Finish analyse generating sample for multi read TE in test_visium.
> Finish Sample test_visium
> Directory MU_Stats created.
> Generating prediction samples: 0it [00:00, ?it/s]
> Start analyse full prediciton data of multi read...
> 
> 100%|██████████| 4992/4992 [00:00<00:00, 95131.92it/s]
> Generating prediction samples: 1it [00:02,  2.11s/it]
> (0,)
> (0,)
> (2, 0)
> (0,)
> (3, 0)
> (0,)
> (4, 0)
> (0,)
> (5, 0)
> (0,)
> (6, 0)
> (0,)
> (7, 0)
> (0,)
> (8, 0)
> (0,)
> (9, 0)
> Finish analyse full prediciton data of multi read.
> Finish saving data for prediction.
> Running on CPU.
> Data Mode:  10X
> AE Settings:  Epoch:      2, Learning Rate: 0.000100
> MLP Settings: Epoch:      2, Learning Rate: 0.000001
> Batch Size:    256
> Searching Bin Size:      5
> Dominate Proportion:     80
> Loading training data for test_visium...
> 
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/train_model.py:384, in MATES_train(data_mode, file_name, bin_size, prop, BATCH_SIZE, AE_LR, MLP_LR, AE_EPOCHS, MLP_EPOCHS, DEVICE)
>     383 try:
> --> 384     Batch_train = unique_TE_matrix.toarray().reshape(i,)
>     385 except:
> 
> ValueError: cannot reshape array of size 0 into shape (1,)
> 
> During handling of the above exception, another exception occurred:
> 
> ValueError                                Traceback (most recent call last)
> Cell In[6], line 12
>       8 data_processor.generate_prediction_sample('exclusive','10X','sample_list.txt', bin_size=5, proportion=80, ref_path="TE_nooverlap.csv", bc_path_file='path_to_cb.txt',cut_off=50)
>      11 ## Step3:Training and prediction
> ---> 12 MATES_model.train('10X', 'sample_list.txt', bin_size = 5, proportion = 80, BATCH_SIZE= 256, 
>      13                   AE_LR = 1e-4, MLP_LR = 1e-6, AE_EPOCHS = 2, MLP_EPOCHS = 2, DEVICE='cpu')
>      14 MATES_model.prediction('exclusive', '10X', 'sample_list.txt', bin_size = 5, proportion = 80, 
>      15                        AE_trained_epochs =2, MLP_trained_epochs=2,DEVICE='cpu')
>      17 ##Step4: Quantify the TE
> 
> File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/MATES_model.py:16, in train(data_mode, sample_list_file, bin_size, proportion, BATCH_SIZE, AE_LR, MLP_LR, AE_EPOCHS, MLP_EPOCHS, DEVICE)
>      14         sample_name = [line.rstrip('\n') for line in sample_file]
>      15     for idx, sample in enumerate(sample_name):
> ---> 16         MATES_train(data_mode, sample, bin_size, proportion, BATCH_SIZE, AE_LR, MLP_LR, 
>      17              AE_EPOCHS, MLP_EPOCHS, DEVICE)
>      19 elif data_mode == 'Smart_seq':
>      20     MATES_train(data_mode, sample_list_file, bin_size, proportion, BATCH_SIZE, AE_LR, MLP_LR, 
>      21              AE_EPOCHS, MLP_EPOCHS, DEVICE)
> 
> File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/train_model.py:386, in MATES_train(data_mode, file_name, bin_size, prop, BATCH_SIZE, AE_LR, MLP_LR, AE_EPOCHS, MLP_EPOCHS, DEVICE)
>     384     Batch_train = unique_TE_matrix.toarray().reshape(i,)
>     385 except:
> --> 386     raise ValueError("The provided bam files don't have enough reads mapped to TE loci.")
>     387 p3 = path + '/Multi_TE_train_'+BIN_SIZE + '_' + PROP+'.npz'
>     388 p4 = path + '/Multi_Batch_train_'+BIN_SIZE + '_' + PROP+'.npz'
> 
> ValueError: The provided bam files don't have enough reads mapped to TE loci.

May I ask if I should modify get_cb.py to obtain the barcode that appears to be correct?
If it should be modified, what is the reason for the above erroneous result?

**Comment by Szym29** [comment]
Hello @DrmBee ,

Thank you for using MATES. If the barcode obtained by using `get_cb.py` is 'CGATTTGTCATTAATG-1', you should not change it to 'CGATTTGTCATTAATG'. Just use format like 'CGATTTGTCATTAATG-1' is correct. 

Thanks,
Yumin

**Comment by DrmBee** [comment]
Hi! @Szym29 :

Thank you very much for your answer!

But if I continue to use the form 'CGATTTGTCATTAATG-1', it will report the following error:

```
[E::hts_open_format] Failed to open file "/home/jialu/ly/new/MATES/example/10X_visium_example/sub_bam_files/test_visium/multi/TAGCTCGCCTGATAAC-1.bam" : Too many open files

ummarizing reads statistics:   0%|          | 127902/45398537 [00:02<12:26, 60640.13it/s]
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[10], line 3
      1 from MATES import bam_processor,data_processor,MATES_model,TE_quantifier
      2 ## Step1: Generate coverage vector
----> 3 bam_processor.split_count_10X_data('exclusive', '10X','sample_list.txt', 'path_to_bam.txt', 'path_to_cb.txt', bc_ind='CB', ref_path = 'TE_nooverlap.bed')
      5 ## Step2: Generate the training and prediction sample
      6 data_processor.calculate_UM_region('exclusive', '10X', 'sample_list.txt', bin_size=5, proportion=80, bc_path_file='path_to_cb.txt',cut_off=50)

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/bam_processor.py:36, in split_count_10X_data(TE_mode, data_mode, sample_list_file, bam_path_file, bc_path_file, bc_ind, ref_path)

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/split_count_10X.py:412, in start_split_count(barcode_field, path_to_bam, barcodes_file, sample, TE_mode, TE_ref_bed_path)

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/split_count_10X.py:337, in generate_matrix(samp_bc, barcodes_file, path_to_bam, TE_ref_bed, coverage_stored_dir, tag_field)

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/split_count_10X.py:31, in write_record_to_barcode(self, rec, barcode, option)

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/split_count_10X.py:37, in _open_file_for_barcode(self, barcode, option)

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/pysam/libcalignmentfile.pyx:751, in pysam.libcalignmentfile.AlignmentFile.__cinit__()

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/pysam/libcalignmentfile.pyx:924, in pysam.libcalignmentfile.AlignmentFile._open()

OSError: [Errno 24] could not open alignment file `/home/jialu/ly/new/MATES/example/10X_visium_example/sub_bam_files/test_visium/multi/TAGCTCGCCTGATAAC-1.bam`: Too many open files
```
May I ask what error this is? Is it due to insufficient hardware performance?

**Comment by Szym29** [comment]
Hi @DrmBee ,

This is an limit in the linux system. Ubuntu system has a default limit for the total number of files opening at the same time. If you are using ubuntu, check some solutions in [stackoverflow](https://stackoverflow.com/questions/880557/socket-accept-too-many-open-files). 

In short, you can try `ulimit -n 1000000` in the terminal before you run MATES. There are some other ways to permanently change this limit mentioned in the link.

Thanks,
Yumin

**Comment by DrmBee** [comment]
Hi! @Szym29 ：

Thank you very much for your friendly and accurate answer! I'm very sorry, I have another small question. In the example of Smart-seq2 Data, does the SRR3934350 output by the following command represent a cell data in human glioblastoma or a type of cell population data?

```
%%bash
echo -e 'sample_list_file:'
cat sample_list_subset.txt | head -n 5
echo -e '\n\nbam_path_file:' 
cat bam_path_file_subset.txt | head -n 5
```
sample_list_file:
SRR3934350
SRR3934360
SRR3934371
SRR3934376
SRR3934387


bam_path_file:
../smart_seq/STAR_Solo_subset/SRR3934350/SRR3934350_Aligned.sortedByCoord.out.bam
../smart_seq/STAR_Solo_subset/SRR3934360/SRR3934360_Aligned.sortedByCoord.out.bam
../smart_seq/STAR_Solo_subset/SRR3934371/SRR3934371_Aligned.sortedByCoord.out.bam
../smart_seq/STAR_Solo_subset/SRR3934376/SRR3934376_Aligned.sortedByCoord.out.bam
../smart_seq/STAR_Solo_subset/SRR3934387/SRR3934387_Aligned.sortedByCoord.out.bam

**Comment by Szym29** [comment]
Hi @DrmBee ,

One sample represent only one cell.

Thanks,
Yumin

**Comment by Songmeijun** [comment]
> 您好 ，
> 
> 这是 linux 系统中的一个限制。Ubuntu 系统对同时打开的文件总数有默认限制。如果您使用的是 ubuntu，请检查 [stackoverflow](https://stackoverflow.com/questions/880557/socket-accept-too-many-open-files) 中的一些解决方案。
> 
> 简而言之，您可以在运行 MATES 之前在终端中尝试。链接中提到还有一些其他方法可以永久更改此限制。`ulimit -n 1000000`
> 
> 谢谢，Yumin

Hello, I'm having the same problem, File : Too many open files. i checked my user limit, which is ulimit -n 1000000. but still this error is reported when running for about two hours. Is there any other solution to keep the task running?

 File "/work/home/acqy5x4ccu/data/test/test_1/simple.py", line 22, in <module>
  File "/work/home/acqy5x4ccu/miniconda3/envs/mates_env/lib/python3.9/site-packages/MATES/MATES_main.py", line 51, in preprocessing
  File "/work/home/acqy5x4ccu/miniconda3/envs/mates_env/lib/python3.9/site-packages/MATES/bam_processor.py", line 37, in split_count_10X_data
  File "/work/home/acqy5x4ccu/miniconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/split_count_10X.py", line 772, in start_split_count
  File "/work/home/acqy5x4ccu/miniconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/split_count_10X.py", line 687, in generate_matrix
  File "/work/home/acqy5x4ccu/miniconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/split_count_10X.py", line 39, in write_record_to_barcode
  File "/work/home/acqy5x4ccu/miniconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/split_count_10X.py", line 51, in _open_file_for_barcode
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 924, in pysam.libcalignmentfile.AlignmentFile._open
OSError: [Errno 24] could not open alignment file `/work/home/acqy5x4ccu/data/test/test_1/sub_bam_files/E30/unique/CCTCAACCACCGGAAA-1.bam`: Too many open files.

(base) [acqy5x4ccu@login02 ~]$ cat /proc/sys/fs/file-max
26156197
(base) [acqy5x4ccu@login02 ~]$ ulimit -n
1000000

**Comment by Szym29** [comment]
Maybe further increase the limitations.
