### ISSUE TITLE
The provided bam files don't have enough reads mapped to TE loci

### ISSUE THREAD

**Issue by LindaMax001** [mcgilldinglab/MATES#28]
Hi ,While trying to use this very nice package but I encounter an error while running step3:

ERROR: MATES_model.train('10X', 'sample_list_file.txt', bin_size = 5, proportion = 80, BATCH_SIZE= 256,
...                   AE_LR = 1e-4, MLP_LR = 1e-6, AE_EPOCHS = 200, MLP_EPOCHS = 200, DEVICE = 'cuda:0')
Data Mode:  10X
AE Settings:  Epoch:    200, Learning Rate: 0.000100
MLP Settings: Epoch:    200, Learning Rate: 0.000001
Batch Size:    256
Searching Bin Size:      5
Dominate Proportion:     80
Loading training data for 01318-1...
Traceback (most recent call last):
  File "miniconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/train_model.py", line 384, in MATES_train
    Batch_train = unique_TE_matrix.toarray().reshape(i,)
ValueError: cannot reshape array of size 0 into shape (1,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/mates_env/lib/python3.9/site-packages/MATES/MATES_model.py", line 16, in train
    MATES_train(data_mode, sample, bin_size, proportion, BATCH_SIZE, AE_LR, MLP_LR,
  File "/miniconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/train_model.py", line 386, in MATES_train
    raise ValueError("The provided bam files don't have enough reads mapped to TE loci.")
ValueError: The provided bam files don't have enough reads mapped to TE loci.
Thank you to all users in advance,
L.

**Comment by Szym29** [comment]
Hello @LindaMax001 ,

Thank you for using MATES! I checked the issue you raised, however the example data works fine in my end. Did you run the provided sample_pipeline.ipynb file step by step? If so, can you delete all MATES generated files and folders like MU_Stats, count_coverage, training_5_80, and so on. Then rerun the jupyter notebook from **Process aligned bam files**?

Thanks,
Yumin

**Comment by LindaMax001** [comment]
Hello Yumin，
Thanks a lot,I used my own data, and I run the data used the  sample_pipeline.ipynb file step by step.Perhaps the bam files have some problem,because the barcode like this,
NH:i:3  HI:i:2  AS:i:98 nM:i:0  UR:Z:ATATTGGTCA CB:Z:D18355E332 DB:Z:CELL118820_N1
TGAATTTATGATTAATATGTTTAATCTTCATCTTCTGAAAAGTCACCAGTTGCACAGTGAGGATCATAAAGGGAGTCT    *       NH:i:3  HI:i:2  AS:i:98 nM:i:0  UR:Z:ATATTGGTCA CB:Z:D18355E332 DB:Z:CELL118820_N1
AAGACTTGGGTTTTTGACCTAACCCTGGTATTTGTGTGACACACGTGTGAATGTGCTCCCTGGGGCAGCACTGAGGAA    *       NH:i:2  HI:i:2  AS:i:92 nM:i:3  UR:Z:GAGAACCACA CB:Z:1781C88E6E DB:Z:CELL90329_N1
CCAGGATCCACTAGAGGGCAGACACTCCCGTGTGTATTTGTGTGGCGCTTGCTGAGTGGTAATAAGAACAGTGCCTGCCAGGATCC    *       NH:i:3  HI:i:2  AS:i:92 nM:i:3  UR:Z:GGCAGCGTCC CB:Z:F53B4CE5E3 DB:Z:CELL46543_N1
GGATCCACTAGAGGGCAGACACACCCGTGTGTATTTGTGTGGCGCTTGCTGAGTGGTAATAAGAACAGTGCCTGCCAGGATCCACT    *       NH:i:1  HI:i:1  AS:i:96 nM:i:1  UR:Z:GGCAGCGTCC CB:Z:F53B4CE5E3 RE:A:I  DB:Z:CELL46543_N1
GGATCCACTAGAGGGCAGACACACCCGTGTGTATTTGTGTGGCGCTTGCTGAGTGGTAATAAGAACAGTGCCTGCCAGGATCCACT    *       NH:i:1  HI:i:1  AS:i:96 nM:i:1  UR:Z:GGCAGCGTCC CB:Z:F53B4CE5E3 RE:A:I  DB:Z:CELL46543_N1
TCCACTAGAGGGCAGACACACCCGTGTGTATTTGTGTGGCGCTTGCTGAGTGGTAATAAGAACAGTGCCTGCCAGGATCCACTAGA    *       NH:i:1  HI:i:1  AS:i:96 nM:i:1  UR:Z:GGCAGCGTCC CB:Z:F53B4CE5E3 RE:A:I  DB:Z:CELL46543_N1
TTGTGTGGCGCTTGCTGAGTGGTAATAAGAACAGTGCCTGCCAGGATCCACTAGAGGGCAGACACACCCGTGTGTATTTGTGTGGC    *       NH:i:3  HI:i:1  AS:i:94 nM:i:2  UR:Z:GGCAGCGTCC CB:Z:F53B4CE5E3 DB:Z:CELL46543_N1
How do I solve this barcode problem? this scRNA-seq data is come from huada.
Thank you again.

**Comment by Szym29** [comment]
Hi @LindaMax001 ,

I am not sure if this issue is raised by barcode or not. Please provide the following information to help resolve your issue.

- I want to know how many cells do you have in this dataset? How large is the bam file (MB, GB)?
- Can you check the folders under count_coverage folder? (Under count_coverage, you should find a folder named by the sample, and in the count_coverage/sample_name/ folder, you should be able to see folders named by the barcode) If folders are generated successfully, then the issue should not be related to barcode.
- Under individual cell barcode folders, can you check TE_multi_Info.csv and TE_unique_Info.csv are generated? These files show the number of unique/multi mapping TE reads in each cell. You can check these files in some cells. 
- Under the MU_Stats/sample_name/ folder you can see a 5_80_stat.csv file, can you check this file is generated and show the content of this file? 

Thanks,
Yumin

**Comment by LindaMax001** [comment]
Hello Yumin,
 Thank you very much for helping me so quickly.
1、The Estimated number of cell is 7135,the Median UMI counts per cell is 787,perhaps the UMI counts cell is too little.The bam file is 37G. I decided to try another sample.
2、In the count_coverage/sample_name/ folder,the folders are generated successfully,It's OK.
3、 Under the unique_TE/multi_TE files,there have some files named like this :Unique_All_MTX.csv.
4、Under the MU_Stats/sample_name/ folder I can see the 5_80_stat.csv file,it's OK.

Thank you again,I will try another sample.

**Comment by Szym29** [comment]
Hi @LindaMax001 ,

From my experience, the bam file has 7000 cells and the size is about 37GB should be fine. MATES should be able to find some TE reads.

Before moving on to another data, I also wanted to help you check the data. 

- Can you check some count_coverage/sample_name/ {barcode_id}/TE_unique_Info.csv files and see if they are empty?

- For MU_Stats/sample_name/ folder/5_80_stat.csv file, is this empty?

Thanks,
Yumin

**Comment by LindaMax001** [comment]
Hello Yumin,
Thank you for you help.
I check the count_coverage/sample_name/ {barcode_id}/TE_unique_Info.csv files,the file is there. There's nothing in it.
MU_Stats/sample_name/ folder/5_80_stat.csv file,The contents are as follows:
,count
LTR,0
LINE,0
SINE,0
DNA,0
Simple_repeat,0
Low_complexity,0
RC,0
snRNA,0
scRNA,0
rRNA,0
tRNA,0
Unspecified,0
Retroposon,0
Satellite,0
srpRNA,0
5_80_stat.csv (END)
Thank you again!

**Comment by LindaMax001** [comment]
Hello Yumin,
I tried another sample,the same error occurred.What causes this problem?
And I used the example data run again use the provided sample_pipeline.ipynb file step by step.Now the new problem arose.
when I run the step3:MATES_model.train('10X', 'test_samplelist.txt', bin_size = 5, proportion = 80, BATCH_SIZE= 256, AE_LR = 1e-6, MLP_LR = 1e-6, AE_EPOCHS = 150, MLP_EPOCHS = 150, DEVICE= 'cuda:0')
the error is: RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
How do I continue?
I'm looking forward to your reply, Thanks a lot!
L.

**Comment by Szym29** [comment]
Hi @LindaMax001 ,

Please check if the CUDA, CUDNN and torch versions are correctly installed. If you don't have an GPU installed (or if you just wanted to continue run the script), you can simply try DEVICE = 'cpu'.

From the 5_80_stat.csv file, the MATES unable to find any TE reads from the bam file. 1, How long does it take for you to run the whole pipeline? 2, Would you be able share part of your data with us? Since you mentioned the data is from huada (like the barcode is D18355E332 which is different from the format of 10X or smart-seq), I can help check if there is any imcompitatbmlility. And get back to you.

If you may, please provide the bam file and the species of the data with us. 

Thanks,
Yumin

**Comment by LindaMax001** [comment]
Hello Yumin,
Thank you for your kind help,I will try the DEVICE = 'cpu' for the sample data.
1、Step1 takes about 2 hours ,other steps are very fast.
2、The bam file is so big,so I sent you the data for 0.05 via email
Thank you again,you are so nice!
L.

**Comment by LindaMax001** [comment]
Hello Yumin,
If I try DEVICE = 'cpu',it's ok.Thank you very much,you are so kind.
Best wish for you.
L.

**Comment by Szym29** [comment]
Hi @LindaMax001 ,

I have received your data and I am testing it. However, it has about 900k cells, which is different from your description above (~7000 cells). I have replied your email, can you check it? 

Thanks,
Yumin

**Comment by Szym29** [comment]
Hi @LindaMax001 ,

I have updated the MATES v0.1.6 to resolve the compatibility issue with the BGI scRNA data. Also, please follow the **Error 2** in [our common Q&A](https://github.com/mcgilldinglab/MATES/blob/main/common_errors.md#error-2-chromosome-name-formatting-conflicts-in-the-input-bam-and-te-reference) to re-format the chromosome style in your bam file to 'chr1', 'chr2', ...,'chrN' before running MATES. 

Please let me know if you have any other issue.

Thanks,
Yumin

**Comment by LindaMax001** [comment]
Hello !
Thank you very much!I'll try it again.
best wishes for you!
L.




锦涵
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mcgilldinglab/MATES"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月31日(星期二) 上午8:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mcgilldinglab/MATES] The provided bam files don't have enough reads mapped to TE loci (Issue #28)





 
Hi @LindaMax001 ,
 
I have updated the MATES v0.1.6 to resolve the compatibility issue with the BGI scRNA data. Also, please follow the Error 2 in our common Q&amp;A to re-format the chromosome style in your bam file to 'chr1', 'chr2', ...,'chrN' before running MATES.
 
Please let me know if you have any other issue.
 
Thanks,
 Yumin
