### ISSUE TITLE
Missing script to split BAM in long read mode

### ISSUE THREAD

**Issue by mcortes-lopez** [mcgilldinglab/MATES#4]
Hi,
I think the following script is missing: `split_bam_by_bc_long.py` it is required when running `bam_processor.split_bam_files()`. So far I modified the `split_bc_long.sh` script by changing `split_bam_by_bc_long.py` for `split_bam_by_bc.py` and it seems to work. I wanted to confirm that this is fine or get the corresponding script. 

Best, 
Mariela

**Comment by Szym29** [comment]
Hi Mariela, 

Thank you very much for your feedback. @RoKsaNne, can you check scripts again and make sure everything is uploaded? 

Regards,
Yumin

**Comment by RoKsaNne** [comment]
Hi Mariela,

Thanks for pointing that out, your attempt is right!

The split_bc_long.sh seems to be an old version so the split_bam_by_bc_long.py didn't change to split_bam_by_bc.py, sorry for the inconvenience, I've updated the split_bc_long.sh now.

Best,
Ruohan

**Comment by RoKsaNne** [comment]
Hi Mariela,

Thanks for pointing that out, your attempt is right!

The split_bc_long.sh seems to be an old version so the split_bam_by_bc_long.py didn't change to split_bam_by_bc.py, sorry for the inconvenience, I've updated the split_bc_long.sh now.

Best,
Ruohan
