### ISSUE TITLE
data_processor.calculate_UM_region is completing before finishing the process

### ISSUE THREAD

**Issue by Citugulia40** [mcgilldinglab/MATES#9]
Hi,

Thanks for developing MATES for TE quantification. I am running mates on one sample from scRNA seq.

The BAM file looks like:

```
`SRR21834807.87030294	16	chr1	97753	0	90M	*	0	0	CAGTAAACTCTATGAGGCAAGCTATAAACATGTAGCATTGTGATTAGGGCTGGTTCTCCTTCTAGAGACATGGTAGGATTGCAATTTCAT	FFFFFFFFF:FFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	CR:Z:CTCTAAGCATAAACCT	UR:Z:TGTAGACCGTAT	CY:Z:FFFFFFFFFFFFFFFF	UY:Z:FFFFFFFFFFFF	NH:i:8	HI:i:1	CB:Z:-	UB:Z:-

SRR21834807.87692915	16	chr1	97753	0	90M	*	0	0	CAGTAAACTCTATGAGGCAAGCTATAAACATGTAGCATTGTGATTAGGGCTGGTTCTCCTTCTAGAGACATGGTAGGATTGCAATTTCAT	FF,FFFFFFFFFFFFFFFFFF:FFFFFFFFF:FFFFFFFFFFFFFFFF,,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFF	CR:Z:CGTACGGGTCATGAGC	UR:Z:CCTGGAAACCAC	CY:Z:FFFFFFFFFFFFFFFF	UY:Z:FFFFFFFFFFFF	NH:i:8	HI:i:1	CB:Z:-	UB:Z:-

SRR21834807.104223931	16	chr1	97753	0	90M	*	0	0	CAGTAAACTCTATGAGGCAAGCTATAAACATGTAGCATTGTGATTAGGGCTGGTTCTCCTTCTAGAGACATGGTAGGATTGCAATTTCAT	FFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	CR:Z:TTAGGCGTCTAATCAG	UR:Z:GGCTTACAACTT	CY:Z::FFFFFFFFFFFFFFF	UY:Z:FFFFFFFFFFFF	NH:i:8	HI:i:1	CB:Z:-	UB:Z:-

SRR21834808.81806189	16	chr1	97753	0	90M	*	0	0	CAGTAAACTCTATGAGGCAAGCTATAAACATGTAGCATTGTGATTAGGGCTGGTTCTCCTTCTAGAGACATGGTAGGATTGCAATTTCAT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	CR:Z:ACGACTTAGTAACCAC	UR:Z:AAGCCACATGGG	CY:Z:FFFFFFFFFFFFFFFF	UY:Z:FFFFFFFFFFFF	NH:i:8	HI:i:1	CB:Z:-	UB:Z:-

SRR21834806.104696679	16	chr1	97753	0	90M	*	0	0	CAGTAAACTCTATGAGGCAAGCTATAAACATGTAGCATTGTGATTAGGGCTGGTTCTACTTCTAGAGACATGGTAGGATTGCAATTTCAT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFF:FFF,FFFFFFFFFFFFFFF,FFFFFFF:FFFFFFFF	CR:Z:ACGCCTTTCCTGATTT	UR:Z:CGTTGTCACTTT	CY:Z:FFFFFFFFFFFFFFFF	UY:Z:FFFFFFFFFFFF	NH:i:8	HI:i:1	CB:Z:-	UB:Z:-

SRR21834808.95011178	16	chr1	97754	0	90M	*	0	0	AGTAAACTCTATGAGGCAAGCTATAAACATGTAGCATTGTGATTAGGGCTGGTTCTCCTTCTAGAGACATGGTAGGATTGCAATTTCATA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF	CR:Z:CAGGTGGGGGACCTTG	UR:Z:AACTTTTACGCA	CY:Z:FFFFFFFFFFFFFFFF	UY:Z:FFFF:FFFFFFF	NH:i:8	HI:i:1	CB:Z:-	UB:Z:-`

```
I have successfully completed the splitting of BAM file and count coverage generation.

But when I am running:

`data_processor.calculate_UM_region('exclusive', '10X', 'samplelist.txt', bin_size=5, proportion=80, ref_path = 'Default', bc_path_file='cb_path.txt')`

This step is not able to finish and also not showing any error like:

```
`Directory MU_Stats created.
Calculating U/M region for sample: sample1
Start Calculating U/M region for cells in sample1...
 97%|█████████▋| 615/635 [00:07<00:00, 83.48it/s] 

Finish calculating U/M region for cells in sample1, finalizing...

Finish finalizing U/M region information for sample1.`
```

And in the next step:

`data_processor.generate_training_sample('10X', 'samplelist.txt', bin_size=5, proportion=80)`

I am getting an error:

```
`Generating training sample for: sample1
Start generating training sample for unqiue read TE in sample1...
Error during training sample generation: [Errno 2] No such file or directory: '/data2/ccitu/software/MATES/anderson/count_coverage/sample1/AAAGGATCACTTACAG/unique.npz'
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[39], line 1
----> 1 data_processor.generate_training_sample('10X', 'samplelist.txt', bin_size=5, proportion=80)

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/data_processor.py:66, in generate_training_sample(data_mode, sample_list_file, bin_size, proportion)
     64     for sample in sample_names:
     65         print(f"Generating training sample for: {sample}")
---> 66         generate_Training(data_mode, sample, bin_size, proportion)
     68 except Exception as e:
     69     print(f"Error during training sample generation: {e}")

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/generateTraining.py:164, in generate_Training(data_mode, file_name, bin_size, prop)
    162 stat = pd.read_csv(csv)
    163 print('Start generating training sample for unqiue read TE in '+sample+"...")
--> 164 unique_vec_matrix, unique_TE_matrix, unique_vec_meta_select = get_unique_sample(cell_ana,stat,data_mode, sample)
    165 TE_train = np.array(unique_vec_matrix)
    166 Batch_train = np.array(unique_TE_matrix)

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/generateTraining.py:32, in get_unique_sample(cell_ana, stat, data_mode, sample)
     30 meta_path = join(cb_path, 'meta.npz')
     31 unique_path = join(cb_path,'unique.npz')
---> 32 if os.stat(unique_path).st_size != 0 and os.path.isfile(unique_path):
     33     unique_matrix = scipy.sparse.load_npz(unique_path).toarray()
     34     meta_matrix = np.load(meta_path,allow_pickle=True)

FileNotFoundError: [Errno 2] No such file or directory: '/data2/ccitu/software/MATES/anderson/count_coverage/sample1/AAAGGATCACTTACAG/unique.npz'`

```
Please help me in solving the error.

Thanks again.

**Comment by Szym29** [comment]
@RoKsaNne

**Comment by Citugulia40** [comment]
Thank you so much

**Comment by Szym29** [comment]
Hi @Citugulia40 ,

Can you use our latest code and see if this issue exist? Did you see any error raised when running bam_processor.count_coverage_vec()?

Thanks,
Yumin

**Comment by Citugulia40** [comment]
Hi, Thanks you so much for your reply.

I have tried MATES with the latest code but still this error persist. No I am not seeing any error with bam_processor.count_coverage_vec().

Thanks for your help!

**Comment by Szym29** [comment]
Hi @Citugulia40 ,

I double checked this error. The reason behind this issue is that some bam files don't have any uniquely mapped TE reads so MATES didn't generate unique.npz for these bam files. I have fixed this issue. 

Please feel free to let me know if you have other questions.

Thanks,
Yumin

**Comment by Citugulia40** [comment]
Hi,

Thank you so much for your response.

I ran MATES again on my data as well as on example dataset, the previous issue is solves.

I am getting another error in:

`MATES_model.train('10X', 'samplelist.txt', bin_size = 5, proportion = 80, BATCH_SIZE= 36, AE_LR = 1e-6, MLP_LR = 1e-6, AE_EPOCHS = 150, MLP_EPOCHS = 150, DEVICE= 'cpu'`

Error:

`Running on CPU.
Data Mode:  10X
AE Settings:  Epoch:    150, Learning Rate: 0.000001
MLP Settings: Epoch:    150, Learning Rate: 0.000001
Batch Size:     36
Searching Bin Size:      5
Dominate Proportion:     80
Loading training data for test...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[42], line 1
----> 1 MATES_model.train('10X', 'samplelist.txt', bin_size = 5, proportion = 80, BATCH_SIZE= 36, AE_LR = 1e-6, MLP_LR = 1e-6, AE_EPOCHS = 150, MLP_EPOCHS = 150, DEVICE= 'cpu')

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/MATES_model.py:16, in train(data_mode, sample_list_file, bin_size, proportion, BATCH_SIZE, AE_LR, MLP_LR, AE_EPOCHS, MLP_EPOCHS, DEVICE)
     14         sample_name = [line.rstrip('\n') for line in sample_file]
     15     for idx, sample in enumerate(sample_name):
---> 16         MATES_train(data_mode, sample, bin_size, proportion, BATCH_SIZE, AE_LR, MLP_LR, 
     17              AE_EPOCHS, MLP_EPOCHS, DEVICE)
     19 elif data_mode == 'Smart_seq':
     20     MATES_train(data_mode, sample_list_file, bin_size, proportion, BATCH_SIZE, AE_LR, MLP_LR, 
     21              AE_EPOCHS, MLP_EPOCHS, DEVICE)

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/scripts/train_model.py:377, in MATES_train(data_mode, file_name, bin_size, prop, BATCH_SIZE, AE_LR, MLP_LR, AE_EPOCHS, MLP_EPOCHS, DEVICE)
    375 TE_train = unique_vec_matrix.toarray()
    376 i = TE_train.shape[0]
--> 377 Batch_train = unique_TE_matrix.toarray().reshape(i,)
    378 p3 = path + '/Multi_TE_train_'+BIN_SIZE + '_' + PROP+'.npz'
    379 p4 = path + '/Multi_Batch_train_'+BIN_SIZE + '_' + PROP+'.npz'

ValueError: cannot reshape array of size 0 into shape (1,)`

**Comment by Szym29** [comment]
Hi @Citugulia40 ,

This error raised from your own data, is it correct? The reason of this issue is that the bam file you provided into MATES doesn't have enough reads that mapped to TE loci. In our original implementation, if a TE sub-family doesn't have more than 50 uniquely mapped reads, the we don't use it for training. You can check the 5_80_stat.csv files generated from the provided sample data and your own sample under MU_STAT/sample_name/. It list the number of TE regions that can be used for training. 

We have added an error handler to make sure users know this error means the training data is insufficient. 

Thanks,
Yumin

**Comment by Citugulia40** [comment]
Hi, Thanks for the reply.

Now I am able to run all steps except the last one

`TE_quantifier.quantify_locus_TE_MTX('exclusive', '10X', 'test_samplelist.txt')`

I am getting an error:

`Finish finalizing Unique TE MTX for sample1
Finalizing locus expression matrix for sample1...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[31], line 1
----> 1 TE_quantifier.quantify_locus_TE_MTX('exclusive', '10X', 'test_samplelist.txt')

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/MATES/TE_quantifier.py:141, in quantify_locus_TE_MTX(TE_mode, data_mode, sample_list_file)
    139 # Add the values for the same features
    140 common_vars = adata_multi.var_names.intersection(adata_unique.var_names)
--> 141 adata_multi[:, common_vars].X += adata_unique[:, common_vars].X
    143 # Concatenate AnnData objects along the features axis (axis=1)
    144 combined_adata = ad.concat([adata_multi, adata_unique[:, adata_unique.var_names.difference(common_vars)]], axis=1)

File ~/anaconda3/envs/mates_env/lib/python3.9/site-packages/scipy/sparse/_base.py:466, in _spbase.__add__(self, other)
    464 elif issparse(other):
    465     if other.shape != self.shape:
--> 466         raise ValueError("inconsistent shapes")
    467     return self._add_sparse(other)
    468 elif isdense(other):

ValueError: inconsistent shapes`

**Comment by Szym29** [comment]
Hi @Citugulia40 ,

I think the issue is that the uniquely mapped TE reads and multi-mapped TE reads do not have any overlapping TE regions. Did you use a subsampled data to run MATES? This issue usually occurs in subsampled bam files. 

We will refine the process and allow users to run MATES smoothly even if their data doesn't have much multi-mapping TE reads.

If you may, we are also open to figure out the reason of this issue using your data.

Thanks,
Yumin

**Comment by Citugulia40** [comment]
Hi, Thanks for the reply.

I am not using the subsample data to run MATES.

https://uthtmc-my.sharepoint.com/my?csf=1&web=1&e=6uMAwA&CID=f05f9df9%2Dc1d4%2D40dc%2D9b34%2D95b14d4cc840&id=%2Fpersonal%2Fcitu%5Fcitu%5Futh%5Ftmc%5Fedu%2FDocuments%2FMATES%5Ffiles&FolderCTID=0x0120007258ADAB24829043963416172E754B19

I have shared my BAM file and barcode file.

Best

**Comment by Szym29** [comment]
Hi @Citugulia40 ,

I am trying to access the data. But got the error"Selected user account does not exist in tenant 'UTHealth Houston' and cannot access the application '00000003-0000-0ff1-ce00-000000000000' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account."

Please kindly grant my permission. We will check the issue asap.

Thanks,
Yumin

**Comment by Citugulia40** [comment]
Can you access the link now

https://uthtmc-my.sharepoint.com/:f:/g/personal/citu_citu_uth_tmc_edu/El9kkjTEzM5OmPF1mn57qc4BSyj2im65kSE-8S99wLlrRg?email=notifications%40github.com&e=Ai5vUf

If now, I can directly attach here.

**Comment by Szym29** [comment]
Hi,

I still cannot open the file. It looks like the data was shared to notifications@github.com. Can you share the data to yumin.zheng@mail.mcgill.ca?

**Comment by Szym29** [comment]
@Citugulia40 , Well received. I will work on it.

**Comment by Szym29** [comment]
@Citugulia40 Is it human or mouse data?

**Comment by Citugulia40** [comment]
Thank you so much! It is human data.

**Comment by Citugulia40** [comment]
Hi @Szym29, 

Is there any problem with my BAM file?

Thanks

**Comment by Szym29** [comment]
Hi @Citugulia40,

I checked your bam file, and it looks fine. And MATES successfully produces results for your given data. I will update MATES v0.1.5 this week and share the script I used to process your data later. 

Thanks,
Yumin

**Comment by Citugulia40** [comment]
Much appreciated!

Thanks for your help.

**Comment by Szym29** [comment]
Hi @Citugulia40 ,

Please install the latest MATESv0.1.5 through git clone. Here is the [script](https://mcgill-my.sharepoint.com/:f:/g/personal/yumin_zheng_mail_mcgill_ca/EnhF9Vml7FBJvqBtPGo6DRMBC_9OsxGRd4irw8Qa_rXQ7w?e=fddba5) and required files to run the script (bc_path_file, bam_path_file, and sample_list_file). You will need to put the data you shared with me in the same folder. And you also need the TE reference files building through `python build_reference.py`. With these, I think you can produce the results.

Thanks,
Yumin

**Comment by Citugulia40** [comment]
Thank you so much for your kind help!
